import assert from "node:assert/strict";
import test from "node:test";
import { computeCandidateHash } from "../../scripts/dev/decision-council-kernel.mjs";
import { buildProposalPacket, buildVotePacket, renderPacketPrompt } from "../../scripts/dev/shadow-council-packet.mjs";
import { buildShadowVoteAssessment, deriveAgentVote, verifyAssessmentHash } from "../../scripts/dev/shadow-council-vote-assessment.mjs";

const hash = c => `sha256:${c.repeat(64)}`;
const base = {councilEpochId:"e",seatId:"seat-openai",riskClass:"R1",taskId:"t",decisionRequestId:"d",contextHash:hash("1"),repositoryHead:"2".repeat(40),decisionQuestion:"Q?",evidence:["E"]};
const proposal = {summary:"S",payload:{x:1}};
const body = {decisionRequestId:"d",taskId:"t",riskClass:"R1",contextHash:base.contextHash,repositoryHead:base.repositoryHead,councilEpochId:"e",proposerSeatId:"seat-openai",candidateOrdinal:0,proposalContent:proposal};
const candidate = {...body,candidateHash:computeCandidateHash(body)};
const input = {decisionRequestId:"d",candidateHash:hash("3"),seatId:"seat-reviewer",councilEpochId:"e",packetHash:hash("4"),outputHash:hash("5"),attestationHash:hash("6"),voteValue:"APPROVE",rationale:"Evidence supports the frozen candidate."};

test("packet hashing and bindings fail closed",()=>{assert.equal(buildProposalPacket(base).packetHash,buildProposalPacket(base).packetHash);assert.notEqual(buildProposalPacket(base).packetHash,buildProposalPacket({...base,decisionQuestion:"X"}).packetHash);assert.throws(()=>buildProposalPacket({...base,evidence:Array(21).fill("x")}));assert.throws(()=>buildVotePacket({...base,candidateHash:hash("0"),candidateDecision:candidate}),/CANDIDATE_HASH_MISMATCH/);assert.throws(()=>buildVotePacket({...base,candidateHash:candidate.candidateHash,candidateDecision:{...candidate,extra:1}}),/INVALID_CANDIDATE/)});
test("reviewer contract changes and proposer contract does not",()=>{const reviewer=buildVotePacket({...base,candidateHash:candidate.candidateHash,candidateDecision:candidate});assert.deepEqual(reviewer.outputContract,{artifact:"ShadowVoteAssessment",requiredFields:["voteValue","rationale"],jsonOnly:true});assert.deepEqual(buildProposalPacket(base).outputContract,{artifact:"AgentProposal",requiredFields:["summary","payload"],jsonOnly:true});const prompt=renderPacketPrompt(reviewer);assert.match(prompt,/non-empty string of at most 1200 characters/);assert.match(prompt,/chain-of-thought/);assert.match(prompt,/hidden reasoning/i);assert.doesNotMatch(prompt,/No explanation/i)});
for(const voteValue of ["APPROVE","REJECT","ABSTAIN"])test(`builds ${voteValue} with rationale`,()=>{const result=buildShadowVoteAssessment({...input,voteValue,rationale:`${voteValue} grounds.`});assert.equal(result.ok,true);assert.equal(verifyAssessmentHash(result.assessment),true);assert.deepEqual(Object.keys(result.assessment),["assessmentHash","decisionRequestId","candidateHash","seatId","councilEpochId","packetHash","outputHash","attestationHash","voteValue","rationale"])});
test("rationale is required, nonblank, and bounded",()=>{const {rationale,...missing}=input;for(const value of [missing,{...input,rationale:""},{...input,rationale:" \t\n"},{...input,rationale:"x".repeat(1201)}])assert.equal(buildShadowVoteAssessment(value).ok,false)});
test("rationale UTF-8 byte limit is distinct from character limit",()=>{const result=buildShadowVoteAssessment({...input,rationale:"😀".repeat(1025)});assert.equal(result.ok,false);assert.equal(result.details.reason,"UTF8_BYTE_LIMIT")});
test("unknown fields and malformed hashes fail closed",()=>{assert.equal(buildShadowVoteAssessment({...input,extra:true}).ok,false);for(const field of ["candidateHash","packetHash","outputHash"])assert.equal(buildShadowVoteAssessment({...input,[field]:"sha256:nope"}).ok,false)});
test("attestationHash null/hash accepted; omission/malformed rejected",()=>{assert.equal(buildShadowVoteAssessment({...input,attestationHash:null}).ok,true);assert.equal(buildShadowVoteAssessment(input).ok,true);const {attestationHash,...missing}=input;assert.equal(buildShadowVoteAssessment(missing).ok,false);assert.equal(buildShadowVoteAssessment({...input,attestationHash:"bad"}).ok,false)});
test("deriveAgentVote projects exactly five fields",()=>{const assessment=buildShadowVoteAssessment(input).assessment;assert.deepEqual(deriveAgentVote(assessment),{decisionRequestId:"d",candidateHash:hash("3"),seatId:"seat-reviewer",councilEpochId:"e",voteValue:"APPROVE"})});
test("deriveAgentVote rejects a voteValue mutation before a vote can be cast",()=>{const assessment=buildShadowVoteAssessment(input).assessment;assert.throws(()=>deriveAgentVote({...assessment,voteValue:"REJECT"}),/ASSESSMENT_HASH_MISMATCH/)});
test("deriveAgentVote cannot substitute a valid assessment from another seat",()=>{const original=buildShadowVoteAssessment(input).assessment;const other=buildShadowVoteAssessment({...input,seatId:"seat-other"}).assessment;assert.throws(()=>deriveAgentVote({...other,seatId:original.seatId}),/ASSESSMENT_HASH_MISMATCH/)});
test("assessment hash detects every body-field mutation",()=>{const a=buildShadowVoteAssessment(input).assessment;assert.equal(verifyAssessmentHash(a),true);const changes={decisionRequestId:"D",candidateHash:hash("7"),seatId:"seat-mutated",councilEpochId:"E",packetHash:hash("8"),outputHash:hash("9"),attestationHash:null,voteValue:"REJECT",rationale:`${a.rationale}!`};for(const [field,value] of Object.entries(changes))assert.equal(verifyAssessmentHash({...a,[field]:value}),false,field)});
